"""initial schema

Revision ID: 05e1c5a7a117
Revises: 
Create Date: 2026-07-18 19:00:31.463211
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e1c5a7a117'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision's schema and data changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=64), nullable=False, comment='文件 ID（UUID）'),
    sa.Column('type', sa.String(length=16), nullable=False, comment='文件类型'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='文件名/标题'),
    sa.Column('thumbnail', sa.String(length=1024), nullable=False, comment='缩略图 URL/路径'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签（JSON 数组）'),
    sa.Column('storage_key', sa.String(length=1024), nullable=False, comment='对象存储中的 key（如 files/xxx.png）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_type'), 'files', ['type'], unique=False)
    op.create_index('ix_files_updated_at', 'files', ['updated_at'], unique=False)
    op.create_table('generation_tasks',
    sa.Column('id', sa.String(length=64), nullable=False, comment='任务 ID'),
    sa.Column('mode', sa.String(length=32), nullable=False, comment='交付方式：streaming / async_polling / ...'),
    sa.Column('task_kind', sa.String(length=64), nullable=False, comment='业务任务类型：用于执行器路由，如 script_divide / video_generation / image_generation'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='任务状态'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度 0-100'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='请求参数（JSON）'),
    sa.Column('result', sa.JSON(), nullable=True, comment='结果（JSON，例如 url、metadata）'),
    sa.Column('error', sa.Text(), nullable=False, comment='失败原因（为空表示无错误）'),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False, comment='是否已请求取消'),
    sa.Column('cancel_requested_at', sa.DateTime(), nullable=True, comment='请求取消时间'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='任务开始执行时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='任务结束时间（成功 / 失败 / 取消）'),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True, comment='取消原因'),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True, comment='实际取消完成时间'),
    sa.Column('executor_type', sa.String(length=32), nullable=True, comment='执行器类型：如 celery'),
    sa.Column('executor_task_id', sa.String(length=128), nullable=True, comment='执行器侧任务 ID，如 celery task id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_tasks_mode'), 'generation_tasks', ['mode'], unique=False)
    op.create_index('ix_generation_tasks_mode_updated_at', 'generation_tasks', ['mode', 'updated_at'], unique=False)
    op.create_index(op.f('ix_generation_tasks_status'), 'generation_tasks', ['status'], unique=False)
    op.create_index('ix_generation_tasks_status_cancel_requested', 'generation_tasks', ['status', 'cancel_requested'], unique=False)
    op.create_index('ix_generation_tasks_status_updated_at', 'generation_tasks', ['status', 'updated_at'], unique=False)
    op.create_index(op.f('ix_generation_tasks_task_kind'), 'generation_tasks', ['task_kind'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False, comment='项目 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=False, comment='项目简介'),
    sa.Column('style', sa.String(length=32), nullable=False, comment='题材/风格'),
    sa.Column('visual_style', sa.String(length=16), nullable=False, comment='画面表现形式（真人/动漫等）'),
    sa.Column('seed', sa.Integer(), nullable=False, comment='随机种子'),
    sa.Column('unify_style', sa.Boolean(), nullable=False, comment='是否统一风格（跨章节）'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度百分比（0-100）'),
    sa.Column('default_video_ratio', sa.String(length=16), nullable=True, comment='项目级默认视频比例（可为空；分镜未覆盖时使用）'),
    sa.Column('stats', sa.JSON(), nullable=False, comment='聚合统计（JSON）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_style', 'projects', ['style'], unique=False)
    op.create_index('ix_projects_updated_at', 'projects', ['updated_at'], unique=False)
    op.create_index('ix_projects_visual_style', 'projects', ['visual_style'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=64), nullable=False, comment='模板 ID（UUID）'),
    sa.Column('category', sa.String(length=32), nullable=False, comment='模板类别'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='模板名称'),
    sa.Column('preview', sa.Text(), nullable=False, comment='预览文案'),
    sa.Column('content', sa.Text(), nullable=False, comment='模板内容'),
    sa.Column('variables', sa.JSON(), nullable=False, comment='变量名列表（JSON 数组）'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为默认提示词（同类别唯一，应用层保证）'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统预置（仅初始化脚本写入，接口层禁止删改）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_category'), 'prompt_templates', ['category'], unique=False)
    op.create_index('ix_prompt_templates_name', 'prompt_templates', ['name'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.String(length=64), nullable=False, comment='供应商 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='供应商名称'),
    sa.Column('base_url', sa.String(length=1024), nullable=False, comment='文本/通用 API Base URL'),
    sa.Column('image_base_url', sa.String(length=1024), nullable=True, comment='图片能力 API Base URL（可选覆盖）'),
    sa.Column('video_base_url', sa.String(length=1024), nullable=True, comment='视频能力 API Base URL（可选覆盖）'),
    sa.Column('api_key', sa.String(length=4096), nullable=False, comment='API Key（敏感）'),
    sa.Column('api_secret', sa.String(length=4096), nullable=False, comment='API Secret（敏感）'),
    sa.Column('description', sa.Text(), nullable=False, comment='说明'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=False)
    op.create_index('ix_providers_status', 'providers', ['status'], unique=False)
    op.create_index('ix_providers_updated_at', 'providers', ['updated_at'], unique=False)
    op.create_table('timeline_clips',
    sa.Column('id', sa.String(length=64), nullable=False, comment='片段 ID'),
    sa.Column('type', sa.String(length=16), nullable=False, comment='片段类型'),
    sa.Column('source_id', sa.String(length=64), nullable=False, comment='来源素材 ID（逻辑引用）'),
    sa.Column('label', sa.String(length=255), nullable=False, comment='显示标签'),
    sa.Column('start', sa.Integer(), nullable=False, comment='起始时间（秒）'),
    sa.Column('end', sa.Integer(), nullable=False, comment='结束时间（秒）'),
    sa.Column('track', sa.Integer(), nullable=False, comment='轨道号'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_clips_source_id'), 'timeline_clips', ['source_id'], unique=False)
    op.create_index('ix_timeline_clips_track', 'timeline_clips', ['track'], unique=False)
    op.create_index(op.f('ix_timeline_clips_type'), 'timeline_clips', ['type'], unique=False)
    op.create_table('actors',
    sa.Column('id', sa.String(length=64), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述'),
    sa.Column('style', sa.String(length=32), nullable=False, comment='题材/风格'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='计划为该演员形象生成的视角图片数量（不含分镜帧）'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签'),
    sa.Column('prompt_template_id', sa.String(length=64), nullable=True, comment='提示词模板 ID'),
    sa.Column('visual_style', sa.String(length=16), nullable=False, comment='画面表现形式（现实/动漫等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_actors_name')
    )
    op.create_index('ix_actors_name', 'actors', ['name'], unique=False)
    op.create_index(op.f('ix_actors_prompt_template_id'), 'actors', ['prompt_template_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.String(length=64), nullable=False, comment='章节 ID'),
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='所属项目 ID'),
    sa.Column('index', sa.Integer(), nullable=False, comment='章节序号（项目内唯一）'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='章节标题'),
    sa.Column('summary', sa.Text(), nullable=False, comment='章节摘要'),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='章节原文（未清洗/可较长）'),
    sa.Column('condensed_text', sa.Text(), nullable=False, comment='由模型精简后的原文（用于抽取/提示词）'),
    sa.Column('storyboard_count', sa.Integer(), nullable=False, comment='分镜数量'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='章节状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'index', name='uq_chapters_project_index')
    )
    op.create_index(op.f('ix_chapters_project_id'), 'chapters', ['project_id'], unique=False)
    op.create_index('ix_chapters_project_title', 'chapters', ['project_id', 'title'], unique=False)
    op.create_index('ix_chapters_status', 'chapters', ['status'], unique=False)
    op.create_index('ix_chapters_updated_at', 'chapters', ['updated_at'], unique=False)
    op.create_table('costumes',
    sa.Column('id', sa.String(length=64), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述'),
    sa.Column('style', sa.String(length=32), nullable=False, comment='题材/风格'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='计划为该服装生成的视角图片数量（不含分镜帧）'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签'),
    sa.Column('prompt_template_id', sa.String(length=64), nullable=True, comment='提示词模板 ID'),
    sa.Column('visual_style', sa.String(length=16), nullable=False, comment='画面表现形式（现实/动漫等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_costumes_name')
    )
    op.create_index('ix_costumes_name', 'costumes', ['name'], unique=False)
    op.create_index(op.f('ix_costumes_prompt_template_id'), 'costumes', ['prompt_template_id'], unique=False)
    op.create_table('generation_task_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联行 ID'),
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='生成任务 ID'),
    sa.Column('resource_type', sa.String(length=32), nullable=False, comment='生成资源类型（如 image/video/text）'),
    sa.Column('relation_type', sa.String(length=32), nullable=False, comment='业务类型（如 prop/costume/scene 等）'),
    sa.Column('relation_entity_id', sa.String(length=64), nullable=False, comment='关联业务实体 ID（如具体的 prop/costume/scene/shot 等对象 ID）'),
    sa.Column('file_id', sa.String(length=64), nullable=True, comment='关联产物文件 ID（files.id；适用于图片/音频/视频）'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='关联状态：accepted=已采用、todo=待操作、rejected=未采用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'resource_type', 'relation_type', 'relation_entity_id', name='uq_task_resource_relation_entity')
    )
    op.create_index('ix_task_link_file_id', 'generation_task_links', ['file_id'], unique=False)
    op.create_index('ix_task_link_relation_entity', 'generation_task_links', ['relation_type', 'relation_entity_id'], unique=False)
    op.create_index('ix_task_link_status_updated_at', 'generation_task_links', ['status', 'updated_at'], unique=False)
    op.create_index('ix_task_link_task_id_resource', 'generation_task_links', ['task_id', 'resource_type'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.String(length=64), nullable=False, comment='模型 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='模型名称'),
    sa.Column('category', sa.String(length=16), nullable=False, comment='模型类别'),
    sa.Column('provider_id', sa.String(length=64), nullable=False, comment='所属供应商 ID'),
    sa.Column('params', sa.JSON(), nullable=False, comment='模型参数（JSON）'),
    sa.Column('description', sa.Text(), nullable=False, comment='说明'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_category'), 'models', ['category'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_index(op.f('ix_models_provider_id'), 'models', ['provider_id'], unique=False)
    op.create_index('ix_models_updated_at', 'models', ['updated_at'], unique=False)
    op.create_table('props',
    sa.Column('id', sa.String(length=64), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述'),
    sa.Column('style', sa.String(length=32), nullable=False, comment='题材/风格'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='计划为该道具生成的视角图片数量（不含分镜帧）'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签'),
    sa.Column('prompt_template_id', sa.String(length=64), nullable=True, comment='提示词模板 ID'),
    sa.Column('visual_style', sa.String(length=16), nullable=False, comment='画面表现形式（现实/动漫等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_props_name')
    )
    op.create_index('ix_props_name', 'props', ['name'], unique=False)
    op.create_index(op.f('ix_props_prompt_template_id'), 'props', ['prompt_template_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.String(length=64), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='名称'),
    sa.Column('description', sa.Text(), nullable=False, comment='描述'),
    sa.Column('style', sa.String(length=32), nullable=False, comment='题材/风格'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='计划为该场景生成的视角图片数量（不含分镜帧）'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签'),
    sa.Column('prompt_template_id', sa.String(length=64), nullable=True, comment='提示词模板 ID'),
    sa.Column('visual_style', sa.String(length=16), nullable=False, comment='画面表现形式（现实/动漫等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_scenes_name')
    )
    op.create_index('ix_scenes_name', 'scenes', ['name'], unique=False)
    op.create_index(op.f('ix_scenes_prompt_template_id'), 'scenes', ['prompt_template_id'], unique=False)
    op.create_table('actor_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='图片行 ID'),
    sa.Column('actor_id', sa.String(length=64), nullable=False, comment='所属演员 ID'),
    sa.Column('file_id', sa.String(length=64), nullable=True, comment='关联的文件 ID（FileItem，可空，支持先创建槽位后填充）'),
    sa.Column('quality_level', sa.String(length=16), nullable=False, comment='精度等级'),
    sa.Column('view_angle', sa.String(length=32), nullable=False, comment='视角'),
    sa.Column('width', sa.Integer(), nullable=True, comment='宽（px）'),
    sa.Column('height', sa.Integer(), nullable=True, comment='高（px）'),
    sa.Column('format', sa.String(length=32), nullable=False, comment='格式'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'quality_level', 'view_angle', name='uq_actor_images_quality_angle')
    )
    op.create_index(op.f('ix_actor_images_actor_id'), 'actor_images', ['actor_id'], unique=False)
    op.create_index(op.f('ix_actor_images_file_id'), 'actor_images', ['file_id'], unique=False)
    op.create_index(op.f('ix_actor_images_quality_level'), 'actor_images', ['quality_level'], unique=False)
    op.create_index(op.f('ix_actor_images_view_angle'), 'actor_images', ['view_angle'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.String(length=64), nullable=False, comment='角色 ID'),
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='所属项目 ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='角色名称'),
    sa.Column('description', sa.Text(), nullable=False, comment='角色描述'),
    sa.Column('style', sa.String(length=32), nullable=False, comment='题材/风格'),
    sa.Column('visual_style', sa.String(length=16), nullable=False, comment='画面表现形式（现实/动漫等）'),
    sa.Column('actor_id', sa.String(length=64), nullable=True, comment='对应演员 ID'),
    sa.Column('costume_id', sa.String(length=64), nullable=True, comment='服装 ID（可空）；应用层需保证与角色同项目或全局'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['costume_id'], ['costumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_characters_project_name')
    )
    op.create_index(op.f('ix_characters_actor_id'), 'characters', ['actor_id'], unique=False)
    op.create_index(op.f('ix_characters_costume_id'), 'characters', ['costume_id'], unique=False)
    op.create_index('ix_characters_name', 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_characters_project_id'), 'characters', ['project_id'], unique=False)
    op.create_table('costume_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='图片行 ID'),
    sa.Column('costume_id', sa.String(length=64), nullable=False, comment='所属服装 ID'),
    sa.Column('file_id', sa.String(length=64), nullable=True, comment='关联的文件 ID（FileItem，可空，支持先创建槽位后填充）'),
    sa.Column('quality_level', sa.String(length=16), nullable=False),
    sa.Column('view_angle', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['costume_id'], ['costumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('costume_id', 'quality_level', 'view_angle', name='uq_costume_images_quality_angle')
    )
    op.create_index(op.f('ix_costume_images_costume_id'), 'costume_images', ['costume_id'], unique=False)
    op.create_index(op.f('ix_costume_images_file_id'), 'costume_images', ['file_id'], unique=False)
    op.create_index(op.f('ix_costume_images_quality_level'), 'costume_images', ['quality_level'], unique=False)
    op.create_index(op.f('ix_costume_images_view_angle'), 'costume_images', ['view_angle'], unique=False)
    op.create_table('model_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='设置行 ID（通常为 1）'),
    sa.Column('default_text_model_id', sa.String(length=64), nullable=True, comment='默认文本模型 ID'),
    sa.Column('default_image_model_id', sa.String(length=64), nullable=True, comment='默认图片模型 ID'),
    sa.Column('default_video_model_id', sa.String(length=64), nullable=True, comment='默认视频模型 ID'),
    sa.Column('api_timeout', sa.Integer(), nullable=False, comment='API 超时（秒）'),
    sa.Column('log_level', sa.String(length=16), nullable=False, comment='日志级别'),
    sa.ForeignKeyConstraint(['default_image_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_text_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_video_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prop_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='图片行 ID'),
    sa.Column('prop_id', sa.String(length=64), nullable=False, comment='所属道具 ID'),
    sa.Column('file_id', sa.String(length=64), nullable=True, comment='关联的文件 ID（FileItem，可空，支持先创建槽位后填充）'),
    sa.Column('quality_level', sa.String(length=16), nullable=False),
    sa.Column('view_angle', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prop_id'], ['props.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prop_id', 'quality_level', 'view_angle', name='uq_prop_images_quality_angle')
    )
    op.create_index(op.f('ix_prop_images_file_id'), 'prop_images', ['file_id'], unique=False)
    op.create_index(op.f('ix_prop_images_prop_id'), 'prop_images', ['prop_id'], unique=False)
    op.create_index(op.f('ix_prop_images_quality_level'), 'prop_images', ['quality_level'], unique=False)
    op.create_index(op.f('ix_prop_images_view_angle'), 'prop_images', ['view_angle'], unique=False)
    op.create_table('scene_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='图片行 ID'),
    sa.Column('scene_id', sa.String(length=64), nullable=False, comment='所属场景 ID'),
    sa.Column('file_id', sa.String(length=64), nullable=True, comment='关联的文件 ID（FileItem，可空，支持先创建槽位后填充）'),
    sa.Column('quality_level', sa.String(length=16), nullable=False, comment='精度等级'),
    sa.Column('view_angle', sa.String(length=32), nullable=False, comment='视角'),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'quality_level', 'view_angle', name='uq_scene_images_quality_angle')
    )
    op.create_index(op.f('ix_scene_images_file_id'), 'scene_images', ['file_id'], unique=False)
    op.create_index(op.f('ix_scene_images_quality_level'), 'scene_images', ['quality_level'], unique=False)
    op.create_index(op.f('ix_scene_images_scene_id'), 'scene_images', ['scene_id'], unique=False)
    op.create_index(op.f('ix_scene_images_view_angle'), 'scene_images', ['view_angle'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.String(length=64), nullable=False, comment='镜头 ID'),
    sa.Column('chapter_id', sa.String(length=64), nullable=False, comment='所属章节 ID'),
    sa.Column('index', sa.Integer(), nullable=False, comment='镜头序号（章节内唯一）'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='镜头标题'),
    sa.Column('thumbnail', sa.String(length=1024), nullable=False, comment='缩略图 URL/路径'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='镜头状态'),
    sa.Column('skip_extraction', sa.Boolean(), nullable=False, comment='是否明确跳过信息提取；为 true 时可直接进入 ready 判定'),
    sa.Column('last_extracted_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次完成信息提取的时间；用于区分未提取与提取结果为空'),
    sa.Column('script_excerpt', sa.Text(), nullable=False, comment='剧本摘录'),
    sa.Column('generated_video_file_id', sa.String(length=64), nullable=True, comment='已生成视频关联的文件 ID（FileItem，type=video）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_video_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'index', name='uq_shots_chapter_index')
    )
    op.create_index(op.f('ix_shots_chapter_id'), 'shots', ['chapter_id'], unique=False)
    op.create_index('ix_shots_chapter_title', 'shots', ['chapter_id', 'title'], unique=False)
    op.create_index(op.f('ix_shots_generated_video_file_id'), 'shots', ['generated_video_file_id'], unique=False)
    op.create_index('ix_shots_status', 'shots', ['status'], unique=False)
    op.create_table('character_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='图片行 ID'),
    sa.Column('character_id', sa.String(length=64), nullable=False, comment='所属角色 ID'),
    sa.Column('file_id', sa.String(length=64), nullable=True, comment='关联的文件 ID（FileItem，可空，支持先创建槽位后填充）'),
    sa.Column('quality_level', sa.String(length=16), nullable=False, comment='精度等级'),
    sa.Column('view_angle', sa.String(length=32), nullable=False, comment='视角'),
    sa.Column('width', sa.Integer(), nullable=True, comment='宽（px）'),
    sa.Column('height', sa.Integer(), nullable=True, comment='高（px）'),
    sa.Column('format', sa.String(length=32), nullable=True, comment='格式'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='是否主图；应用层需保证同一角色下至多一张主图'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'quality_level', 'view_angle', name='uq_character_images_quality_angle')
    )
    op.create_index(op.f('ix_character_images_character_id'), 'character_images', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_images_file_id'), 'character_images', ['file_id'], unique=False)
    op.create_index(op.f('ix_character_images_quality_level'), 'character_images', ['quality_level'], unique=False)
    op.create_index(op.f('ix_character_images_view_angle'), 'character_images', ['view_angle'], unique=False)
    op.create_table('character_prop_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联行 ID'),
    sa.Column('character_id', sa.String(length=64), nullable=False, comment='角色 ID'),
    sa.Column('prop_id', sa.String(length=64), nullable=False, comment='道具 ID'),
    sa.Column('index', sa.Integer(), nullable=False, comment='角色道具排序'),
    sa.Column('note', sa.Text(), nullable=False, comment='备注（可选）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prop_id'], ['props.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'index', name='uq_character_prop_links_character_index'),
    sa.UniqueConstraint('character_id', 'prop_id', name='uq_character_prop_links_character_prop')
    )
    op.create_index(op.f('ix_character_prop_links_character_id'), 'character_prop_links', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_prop_links_prop_id'), 'character_prop_links', ['prop_id'], unique=False)
    op.create_table('file_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='行 ID'),
    sa.Column('file_id', sa.String(length=64), nullable=False, comment='文件 ID'),
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='项目 ID'),
    sa.Column('chapter_id', sa.String(length=64), nullable=True, comment='章节 ID（可空）'),
    sa.Column('shot_id', sa.String(length=64), nullable=True, comment='镜头 ID（可空）'),
    sa.Column('usage_kind', sa.String(length=32), nullable=False, comment='用途类型'),
    sa.Column('source_ref', sa.String(length=128), nullable=False, comment='幂等键（如同一槽位 upsert；无则空串）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'usage_kind', 'source_ref', name='uq_file_usages_file_kind_ref')
    )
    op.create_index(op.f('ix_file_usages_chapter_id'), 'file_usages', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_file_usages_file_id'), 'file_usages', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_usages_project_id'), 'file_usages', ['project_id'], unique=False)
    op.create_index('ix_file_usages_project_shot', 'file_usages', ['project_id', 'shot_id'], unique=False)
    op.create_index(op.f('ix_file_usages_shot_id'), 'file_usages', ['shot_id'], unique=False)
    op.create_index(op.f('ix_file_usages_usage_kind'), 'file_usages', ['usage_kind'], unique=False)
    op.create_table('project_actor_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联行 ID'),
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='项目 ID'),
    sa.Column('chapter_id', sa.String(length=64), nullable=True, comment='章节 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=True, comment='镜头 ID'),
    sa.Column('actor_id', sa.String(length=64), nullable=False, comment='演员 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'project_id', 'chapter_id', 'shot_id', name='uq_project_actor_links_actor_scope')
    )
    op.create_index(op.f('ix_project_actor_links_actor_id'), 'project_actor_links', ['actor_id'], unique=False)
    op.create_index(op.f('ix_project_actor_links_chapter_id'), 'project_actor_links', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_project_actor_links_project_id'), 'project_actor_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_actor_links_shot_id'), 'project_actor_links', ['shot_id'], unique=False)
    op.create_table('project_costume_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联行 ID'),
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='项目 ID'),
    sa.Column('chapter_id', sa.String(length=64), nullable=True, comment='章节 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=True, comment='镜头 ID'),
    sa.Column('costume_id', sa.String(length=64), nullable=False, comment='服装 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['costume_id'], ['costumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('costume_id', 'project_id', 'chapter_id', 'shot_id', name='uq_project_costume_links_costume_scope')
    )
    op.create_index(op.f('ix_project_costume_links_chapter_id'), 'project_costume_links', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_project_costume_links_costume_id'), 'project_costume_links', ['costume_id'], unique=False)
    op.create_index(op.f('ix_project_costume_links_project_id'), 'project_costume_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_costume_links_shot_id'), 'project_costume_links', ['shot_id'], unique=False)
    op.create_table('project_prop_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联行 ID'),
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='项目 ID'),
    sa.Column('chapter_id', sa.String(length=64), nullable=True, comment='章节 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=True, comment='镜头 ID'),
    sa.Column('prop_id', sa.String(length=64), nullable=False, comment='道具 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prop_id'], ['props.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prop_id', 'project_id', 'chapter_id', 'shot_id', name='uq_project_prop_links_prop_scope')
    )
    op.create_index(op.f('ix_project_prop_links_chapter_id'), 'project_prop_links', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_project_prop_links_project_id'), 'project_prop_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_prop_links_prop_id'), 'project_prop_links', ['prop_id'], unique=False)
    op.create_index(op.f('ix_project_prop_links_shot_id'), 'project_prop_links', ['shot_id'], unique=False)
    op.create_table('project_scene_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联行 ID'),
    sa.Column('project_id', sa.String(length=64), nullable=False, comment='项目 ID'),
    sa.Column('chapter_id', sa.String(length=64), nullable=True, comment='章节 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=True, comment='镜头 ID'),
    sa.Column('scene_id', sa.String(length=64), nullable=False, comment='场景 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'project_id', 'chapter_id', 'shot_id', name='uq_project_scene_links_scene_scope')
    )
    op.create_index(op.f('ix_project_scene_links_chapter_id'), 'project_scene_links', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_project_scene_links_project_id'), 'project_scene_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_scene_links_scene_id'), 'project_scene_links', ['scene_id'], unique=False)
    op.create_index(op.f('ix_project_scene_links_shot_id'), 'project_scene_links', ['shot_id'], unique=False)
    op.create_table('shot_character_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='关联行 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=False, comment='镜头 ID'),
    sa.Column('character_id', sa.String(length=64), nullable=False, comment='角色 ID'),
    sa.Column('index', sa.Integer(), nullable=False, comment='镜头内角色排序'),
    sa.Column('note', sa.Text(), nullable=False, comment='备注（可选）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'character_id', name='uq_shot_character_links_shot_character'),
    sa.UniqueConstraint('shot_id', 'index', name='uq_shot_character_links_shot_index')
    )
    op.create_index(op.f('ix_shot_character_links_character_id'), 'shot_character_links', ['character_id'], unique=False)
    op.create_index(op.f('ix_shot_character_links_shot_id'), 'shot_character_links', ['shot_id'], unique=False)
    op.create_table('shot_details',
    sa.Column('id', sa.String(length=64), nullable=False, comment='镜头 ID（与 shots.id 共享主键）'),
    sa.Column('camera_shot', sa.String(length=16), nullable=False, comment='景别（存 code：ECU/CU/MCU/MS/MLS/LS/ELS；展示可用 schemas.SHOT_TYPE_ZH）'),
    sa.Column('angle', sa.String(length=16), nullable=False, comment='机位角度（存 code：EYE_LEVEL/HIGH_ANGLE/...；展示可用 schemas.CAMERA_ANGLE_ZH）'),
    sa.Column('movement', sa.String(length=16), nullable=False, comment='运镜方式（存 code：STATIC/PAN/...；展示可用 schemas.CAMERA_MOVEMENT_ZH）'),
    sa.Column('scene_id', sa.String(length=64), nullable=True, comment='关联场景 ID（可空）；应用层需保证与镜头所属项目一致或全局'),
    sa.Column('duration', sa.Integer(), nullable=False, comment='时长（秒）；镜头唯一时长来源'),
    sa.Column('override_video_ratio', sa.String(length=16), nullable=True, comment='分镜级视频比例覆盖（为空表示继承项目默认）'),
    sa.Column('mood_tags', sa.JSON(), nullable=False, comment='情绪标签（JSON 数组）'),
    sa.Column('atmosphere', sa.Text(), nullable=False, comment='氛围描述'),
    sa.Column('follow_atmosphere', sa.Boolean(), nullable=False, comment='是否沿用氛围'),
    sa.Column('has_bgm', sa.Boolean(), nullable=False, comment='是否包含 BGM'),
    sa.Column('vfx_type', sa.String(length=32), nullable=False, comment='视效类型（存 code；展示可用 schemas.VFX_TYPE_ZH）'),
    sa.Column('vfx_note', sa.Text(), nullable=False, comment='视效说明（简短可执行）'),
    sa.Column('description', sa.Text(), nullable=False, comment='分镜整体描述（用于提示词补充）'),
    sa.Column('action_beats', sa.JSON(), nullable=False, comment='镜头动作拍点（按时间顺序排列，用于关键帧与视频生成）'),
    sa.Column('prompt_template_id', sa.String(length=64), nullable=True, comment='分镜提示词模板 ID（可选）'),
    sa.Column('first_frame_prompt', sa.Text(), nullable=False, comment='镜头分镜首帧提示词'),
    sa.Column('last_frame_prompt', sa.Text(), nullable=False, comment='镜头分镜尾帧提示词'),
    sa.Column('key_frame_prompt', sa.Text(), nullable=False, comment='镜头分镜关键帧提示词'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['shots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shot_details_angle', 'shot_details', ['angle'], unique=False)
    op.create_index('ix_shot_details_camera_shot', 'shot_details', ['camera_shot'], unique=False)
    op.create_index('ix_shot_details_prompt_template_id', 'shot_details', ['prompt_template_id'], unique=False)
    op.create_index(op.f('ix_shot_details_scene_id'), 'shot_details', ['scene_id'], unique=False)
    op.create_table('shot_extracted_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='候选项自增 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=False, comment='所属镜头 ID'),
    sa.Column('candidate_type', sa.String(length=32), nullable=False, comment='候选类型：character/scene/prop/costume'),
    sa.Column('candidate_name', sa.String(length=255), nullable=False, comment='候选名称'),
    sa.Column('candidate_status', sa.String(length=32), nullable=False, comment='候选确认状态：pending/linked/ignored'),
    sa.Column('linked_entity_id', sa.String(length=64), nullable=True, comment='已关联时对应的目标实体 ID'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='候选来源，当前固定为 extraction'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='保留提取附加信息，如 description/thumbnail/file_id/confidence 等'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='候选项被确认（关联/忽略）时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'candidate_type', 'candidate_name', name='uq_shot_candidate_name')
    )
    op.create_index(op.f('ix_shot_extracted_candidates_candidate_status'), 'shot_extracted_candidates', ['candidate_status'], unique=False)
    op.create_index(op.f('ix_shot_extracted_candidates_candidate_type'), 'shot_extracted_candidates', ['candidate_type'], unique=False)
    op.create_index(op.f('ix_shot_extracted_candidates_linked_entity_id'), 'shot_extracted_candidates', ['linked_entity_id'], unique=False)
    op.create_index(op.f('ix_shot_extracted_candidates_shot_id'), 'shot_extracted_candidates', ['shot_id'], unique=False)
    op.create_index('ix_shot_extracted_candidates_shot_type', 'shot_extracted_candidates', ['shot_id', 'candidate_type'], unique=False)
    op.create_table('shot_dialog_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='对话行自增 ID'),
    sa.Column('shot_detail_id', sa.String(length=64), nullable=False, comment='所属镜头细节 ID'),
    sa.Column('index', sa.Integer(), nullable=False, comment='行号（镜头内排序）'),
    sa.Column('text', sa.Text(), nullable=False, comment='台词内容'),
    sa.Column('line_mode', sa.String(length=16), nullable=False, comment='对白模式（DIALOGUE/VOICE_OVER/OFF_SCREEN/PHONE；对齐 schemas.DIALOGUE_LINE_MODE_ZH）'),
    sa.Column('speaker_character_id', sa.String(length=64), nullable=True, comment='说话角色 ID；应用层需保证与镜头所属项目一致'),
    sa.Column('target_character_id', sa.String(length=64), nullable=True, comment='听者角色 ID；应用层需保证与镜头所属项目一致'),
    sa.Column('speaker_name', sa.String(length=255), nullable=True, comment='说话角色名称（用于从提取结果回填角色关联；可空）'),
    sa.Column('target_name', sa.String(length=255), nullable=True, comment='听者角色名称（用于从提取结果回填角色关联；可空）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shot_detail_id'], ['shot_details.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_detail_id', 'index', name='uq_shot_dialog_lines_shot_index')
    )
    op.create_index(op.f('ix_shot_dialog_lines_shot_detail_id'), 'shot_dialog_lines', ['shot_detail_id'], unique=False)
    op.create_index(op.f('ix_shot_dialog_lines_speaker_character_id'), 'shot_dialog_lines', ['speaker_character_id'], unique=False)
    op.create_index(op.f('ix_shot_dialog_lines_speaker_name'), 'shot_dialog_lines', ['speaker_name'], unique=False)
    op.create_index(op.f('ix_shot_dialog_lines_target_character_id'), 'shot_dialog_lines', ['target_character_id'], unique=False)
    op.create_index(op.f('ix_shot_dialog_lines_target_name'), 'shot_dialog_lines', ['target_name'], unique=False)
    op.create_table('shot_frame_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='图片行 ID'),
    sa.Column('shot_detail_id', sa.String(length=64), nullable=False, comment='所属镜头细节 ID'),
    sa.Column('frame_type', sa.String(length=16), nullable=False, comment='帧类型：first/last/key'),
    sa.Column('file_id', sa.String(length=64), nullable=True, comment='关联的文件 ID（FileItem）'),
    sa.Column('width', sa.Integer(), nullable=True, comment='宽（px）'),
    sa.Column('height', sa.Integer(), nullable=True, comment='高（px）'),
    sa.Column('format', sa.String(length=32), nullable=False, comment='格式'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_detail_id'], ['shot_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_detail_id', 'frame_type', name='uq_shot_frame_images_detail_type')
    )
    op.create_index(op.f('ix_shot_frame_images_file_id'), 'shot_frame_images', ['file_id'], unique=False)
    op.create_index(op.f('ix_shot_frame_images_frame_type'), 'shot_frame_images', ['frame_type'], unique=False)
    op.create_index(op.f('ix_shot_frame_images_shot_detail_id'), 'shot_frame_images', ['shot_detail_id'], unique=False)
    op.create_table('shot_extracted_dialogue_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='对白候选自增 ID'),
    sa.Column('shot_id', sa.String(length=64), nullable=False, comment='所属镜头 ID'),
    sa.Column('index', sa.Integer(), nullable=False, comment='镜头内对白候选排序'),
    sa.Column('text', sa.Text(), nullable=False, comment='提取出的对白文本'),
    sa.Column('line_mode', sa.String(length=16), nullable=False, comment='对白模式（DIALOGUE/VOICE_OVER/OFF_SCREEN/PHONE）'),
    sa.Column('speaker_name', sa.String(length=255), nullable=True, comment='说话角色名称（可空）'),
    sa.Column('target_name', sa.String(length=255), nullable=True, comment='听者角色名称（可空）'),
    sa.Column('candidate_status', sa.String(length=32), nullable=False, comment='对白候选确认状态：pending/accepted/ignored'),
    sa.Column('linked_dialog_line_id', sa.Integer(), nullable=True, comment='已接受时写入的对白行 ID'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='候选来源，当前固定为 extraction'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='保留提取附加信息，便于后续扩展'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='对白候选被确认（接受/忽略）时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['linked_dialog_line_id'], ['shot_dialog_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shot_dialogue_candidates_shot_status', 'shot_extracted_dialogue_candidates', ['shot_id', 'candidate_status'], unique=False)
    op.create_index(op.f('ix_shot_extracted_dialogue_candidates_candidate_status'), 'shot_extracted_dialogue_candidates', ['candidate_status'], unique=False)
    op.create_index(op.f('ix_shot_extracted_dialogue_candidates_linked_dialog_line_id'), 'shot_extracted_dialogue_candidates', ['linked_dialog_line_id'], unique=False)
    op.create_index(op.f('ix_shot_extracted_dialogue_candidates_shot_id'), 'shot_extracted_dialogue_candidates', ['shot_id'], unique=False)
    op.create_index(op.f('ix_shot_extracted_dialogue_candidates_speaker_name'), 'shot_extracted_dialogue_candidates', ['speaker_name'], unique=False)
    op.create_index(op.f('ix_shot_extracted_dialogue_candidates_target_name'), 'shot_extracted_dialogue_candidates', ['target_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision where the operation is safely reversible."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shot_extracted_dialogue_candidates_target_name'), table_name='shot_extracted_dialogue_candidates')
    op.drop_index(op.f('ix_shot_extracted_dialogue_candidates_speaker_name'), table_name='shot_extracted_dialogue_candidates')
    op.drop_index(op.f('ix_shot_extracted_dialogue_candidates_shot_id'), table_name='shot_extracted_dialogue_candidates')
    op.drop_index(op.f('ix_shot_extracted_dialogue_candidates_linked_dialog_line_id'), table_name='shot_extracted_dialogue_candidates')
    op.drop_index(op.f('ix_shot_extracted_dialogue_candidates_candidate_status'), table_name='shot_extracted_dialogue_candidates')
    op.drop_index('ix_shot_dialogue_candidates_shot_status', table_name='shot_extracted_dialogue_candidates')
    op.drop_table('shot_extracted_dialogue_candidates')
    op.drop_index(op.f('ix_shot_frame_images_shot_detail_id'), table_name='shot_frame_images')
    op.drop_index(op.f('ix_shot_frame_images_frame_type'), table_name='shot_frame_images')
    op.drop_index(op.f('ix_shot_frame_images_file_id'), table_name='shot_frame_images')
    op.drop_table('shot_frame_images')
    op.drop_index(op.f('ix_shot_dialog_lines_target_name'), table_name='shot_dialog_lines')
    op.drop_index(op.f('ix_shot_dialog_lines_target_character_id'), table_name='shot_dialog_lines')
    op.drop_index(op.f('ix_shot_dialog_lines_speaker_name'), table_name='shot_dialog_lines')
    op.drop_index(op.f('ix_shot_dialog_lines_speaker_character_id'), table_name='shot_dialog_lines')
    op.drop_index(op.f('ix_shot_dialog_lines_shot_detail_id'), table_name='shot_dialog_lines')
    op.drop_table('shot_dialog_lines')
    op.drop_index('ix_shot_extracted_candidates_shot_type', table_name='shot_extracted_candidates')
    op.drop_index(op.f('ix_shot_extracted_candidates_shot_id'), table_name='shot_extracted_candidates')
    op.drop_index(op.f('ix_shot_extracted_candidates_linked_entity_id'), table_name='shot_extracted_candidates')
    op.drop_index(op.f('ix_shot_extracted_candidates_candidate_type'), table_name='shot_extracted_candidates')
    op.drop_index(op.f('ix_shot_extracted_candidates_candidate_status'), table_name='shot_extracted_candidates')
    op.drop_table('shot_extracted_candidates')
    op.drop_index(op.f('ix_shot_details_scene_id'), table_name='shot_details')
    op.drop_index('ix_shot_details_prompt_template_id', table_name='shot_details')
    op.drop_index('ix_shot_details_camera_shot', table_name='shot_details')
    op.drop_index('ix_shot_details_angle', table_name='shot_details')
    op.drop_table('shot_details')
    op.drop_index(op.f('ix_shot_character_links_shot_id'), table_name='shot_character_links')
    op.drop_index(op.f('ix_shot_character_links_character_id'), table_name='shot_character_links')
    op.drop_table('shot_character_links')
    op.drop_index(op.f('ix_project_scene_links_shot_id'), table_name='project_scene_links')
    op.drop_index(op.f('ix_project_scene_links_scene_id'), table_name='project_scene_links')
    op.drop_index(op.f('ix_project_scene_links_project_id'), table_name='project_scene_links')
    op.drop_index(op.f('ix_project_scene_links_chapter_id'), table_name='project_scene_links')
    op.drop_table('project_scene_links')
    op.drop_index(op.f('ix_project_prop_links_shot_id'), table_name='project_prop_links')
    op.drop_index(op.f('ix_project_prop_links_prop_id'), table_name='project_prop_links')
    op.drop_index(op.f('ix_project_prop_links_project_id'), table_name='project_prop_links')
    op.drop_index(op.f('ix_project_prop_links_chapter_id'), table_name='project_prop_links')
    op.drop_table('project_prop_links')
    op.drop_index(op.f('ix_project_costume_links_shot_id'), table_name='project_costume_links')
    op.drop_index(op.f('ix_project_costume_links_project_id'), table_name='project_costume_links')
    op.drop_index(op.f('ix_project_costume_links_costume_id'), table_name='project_costume_links')
    op.drop_index(op.f('ix_project_costume_links_chapter_id'), table_name='project_costume_links')
    op.drop_table('project_costume_links')
    op.drop_index(op.f('ix_project_actor_links_shot_id'), table_name='project_actor_links')
    op.drop_index(op.f('ix_project_actor_links_project_id'), table_name='project_actor_links')
    op.drop_index(op.f('ix_project_actor_links_chapter_id'), table_name='project_actor_links')
    op.drop_index(op.f('ix_project_actor_links_actor_id'), table_name='project_actor_links')
    op.drop_table('project_actor_links')
    op.drop_index(op.f('ix_file_usages_usage_kind'), table_name='file_usages')
    op.drop_index(op.f('ix_file_usages_shot_id'), table_name='file_usages')
    op.drop_index('ix_file_usages_project_shot', table_name='file_usages')
    op.drop_index(op.f('ix_file_usages_project_id'), table_name='file_usages')
    op.drop_index(op.f('ix_file_usages_file_id'), table_name='file_usages')
    op.drop_index(op.f('ix_file_usages_chapter_id'), table_name='file_usages')
    op.drop_table('file_usages')
    op.drop_index(op.f('ix_character_prop_links_prop_id'), table_name='character_prop_links')
    op.drop_index(op.f('ix_character_prop_links_character_id'), table_name='character_prop_links')
    op.drop_table('character_prop_links')
    op.drop_index(op.f('ix_character_images_view_angle'), table_name='character_images')
    op.drop_index(op.f('ix_character_images_quality_level'), table_name='character_images')
    op.drop_index(op.f('ix_character_images_file_id'), table_name='character_images')
    op.drop_index(op.f('ix_character_images_character_id'), table_name='character_images')
    op.drop_table('character_images')
    op.drop_index('ix_shots_status', table_name='shots')
    op.drop_index(op.f('ix_shots_generated_video_file_id'), table_name='shots')
    op.drop_index('ix_shots_chapter_title', table_name='shots')
    op.drop_index(op.f('ix_shots_chapter_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_scene_images_view_angle'), table_name='scene_images')
    op.drop_index(op.f('ix_scene_images_scene_id'), table_name='scene_images')
    op.drop_index(op.f('ix_scene_images_quality_level'), table_name='scene_images')
    op.drop_index(op.f('ix_scene_images_file_id'), table_name='scene_images')
    op.drop_table('scene_images')
    op.drop_index(op.f('ix_prop_images_view_angle'), table_name='prop_images')
    op.drop_index(op.f('ix_prop_images_quality_level'), table_name='prop_images')
    op.drop_index(op.f('ix_prop_images_prop_id'), table_name='prop_images')
    op.drop_index(op.f('ix_prop_images_file_id'), table_name='prop_images')
    op.drop_table('prop_images')
    op.drop_table('model_settings')
    op.drop_index(op.f('ix_costume_images_view_angle'), table_name='costume_images')
    op.drop_index(op.f('ix_costume_images_quality_level'), table_name='costume_images')
    op.drop_index(op.f('ix_costume_images_file_id'), table_name='costume_images')
    op.drop_index(op.f('ix_costume_images_costume_id'), table_name='costume_images')
    op.drop_table('costume_images')
    op.drop_index(op.f('ix_characters_project_id'), table_name='characters')
    op.drop_index('ix_characters_name', table_name='characters')
    op.drop_index(op.f('ix_characters_costume_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_actor_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_actor_images_view_angle'), table_name='actor_images')
    op.drop_index(op.f('ix_actor_images_quality_level'), table_name='actor_images')
    op.drop_index(op.f('ix_actor_images_file_id'), table_name='actor_images')
    op.drop_index(op.f('ix_actor_images_actor_id'), table_name='actor_images')
    op.drop_table('actor_images')
    op.drop_index(op.f('ix_scenes_prompt_template_id'), table_name='scenes')
    op.drop_index('ix_scenes_name', table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_props_prompt_template_id'), table_name='props')
    op.drop_index('ix_props_name', table_name='props')
    op.drop_table('props')
    op.drop_index('ix_models_updated_at', table_name='models')
    op.drop_index(op.f('ix_models_provider_id'), table_name='models')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_category'), table_name='models')
    op.drop_table('models')
    op.drop_index('ix_task_link_task_id_resource', table_name='generation_task_links')
    op.drop_index('ix_task_link_status_updated_at', table_name='generation_task_links')
    op.drop_index('ix_task_link_relation_entity', table_name='generation_task_links')
    op.drop_index('ix_task_link_file_id', table_name='generation_task_links')
    op.drop_table('generation_task_links')
    op.drop_index(op.f('ix_costumes_prompt_template_id'), table_name='costumes')
    op.drop_index('ix_costumes_name', table_name='costumes')
    op.drop_table('costumes')
    op.drop_index('ix_chapters_updated_at', table_name='chapters')
    op.drop_index('ix_chapters_status', table_name='chapters')
    op.drop_index('ix_chapters_project_title', table_name='chapters')
    op.drop_index(op.f('ix_chapters_project_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_actors_prompt_template_id'), table_name='actors')
    op.drop_index('ix_actors_name', table_name='actors')
    op.drop_table('actors')
    op.drop_index(op.f('ix_timeline_clips_type'), table_name='timeline_clips')
    op.drop_index('ix_timeline_clips_track', table_name='timeline_clips')
    op.drop_index(op.f('ix_timeline_clips_source_id'), table_name='timeline_clips')
    op.drop_table('timeline_clips')
    op.drop_index('ix_providers_updated_at', table_name='providers')
    op.drop_index('ix_providers_status', table_name='providers')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    op.drop_index('ix_prompt_templates_name', table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_category'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index('ix_projects_visual_style', table_name='projects')
    op.drop_index('ix_projects_updated_at', table_name='projects')
    op.drop_index('ix_projects_style', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_generation_tasks_task_kind'), table_name='generation_tasks')
    op.drop_index('ix_generation_tasks_status_updated_at', table_name='generation_tasks')
    op.drop_index('ix_generation_tasks_status_cancel_requested', table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_status'), table_name='generation_tasks')
    op.drop_index('ix_generation_tasks_mode_updated_at', table_name='generation_tasks')
    op.drop_index(op.f('ix_generation_tasks_mode'), table_name='generation_tasks')
    op.drop_table('generation_tasks')
    op.drop_index('ix_files_updated_at', table_name='files')
    op.drop_index(op.f('ix_files_type'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
